apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-shrink
  labels:
    app: tigergraph
spec:
  template:
    metadata:
      labels:
        app: tigergraph
    spec:
      serviceAccountName: tigergraph-installer
      initContainers:
      - name: init-cluster-shrink
        image: tigergraph/tigergraph-k8s-installer:3.5.0
        env:
        - name: POD_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: pod.prefix
        command: 
        - "/bin/sh"
        - "-c"
        - >
          set -e;
          kubectl rollout status --watch --timeout=2h statefulset ${POD_PREFIX};
          sleep 5;
      containers:
      - name: cluster-shrink
        image: tigergraph/tigergraph-k8s-installer:3.5.0
        env:
        - name: CLUSTER_SIZE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: cluster_size
        - name: CLUSTER_SIZE_STAGING
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: cluster_size.staging
        - name: HA_STAGING
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ha.staging
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: service.headless.name
        - name: POD_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: pod.prefix
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: namespace
        command:
        - "/bin/sh"
        - "-c"
        - |
          hostlist="";
          for i in `seq $CLUSTER_SIZE_STAGING $(($CLUSTER_SIZE-1))`
          do
            host="m$(($i+1)):${POD_PREFIX}-$i.tigergraph";
            if [[ -z "$hostlist" ]]; then
              hostlist="$host";
            else
              hostlist="${hostlist},${host}";
            fi
          done;
          kubectl exec -n ${NAMESPACE} -i ${POD_PREFIX}-0 -- /home/tigergraph/tigergraph/app/cmd/gadmin cluster shrink ${hostlist} --ha=${HA_STAGING} -y;
      restartPolicy: Never
  backoffLimit: 0
